{
    "album": {
        "album_group": "album",
        "album_type": "album",
        "artists": [
            {
                "external_urls": {
                    "spotify": "https://open.spotify.com/artist/06HL4z0CvFAxyc27GXpf02"
                },
                "href": "https://api.spotify.com/v1/artists/06HL4z0CvFAxyc27GXpf02",
                "id": "06HL4z0CvFAxyc27GXpf02",
                "name": "Taylor Swift",
                "type": "artist",
                "uri": "spotify:artist:06HL4z0CvFAxyc27GXpf02",
            }
        ],
        "available_markets": [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW",
        ],
        "external_urls": {
            "spotify": "https://open.spotify.com/album/2fenSS68JI1h4Fo296JfGr"
        },
        "href": "https://api.spotify.com/v1/albums/2fenSS68JI1h4Fo296JfGr",
        "id": "2fenSS68JI1h4Fo296JfGr",
        "images": [
            {
                "height": 640,
                "url": "https://i.scdn.co/image/ab67616d0000b27395f754318336a07e85ec59bc",
                "width": 640,
            },
            {
                "height": 300,
                "url": "https://i.scdn.co/image/ab67616d00001e0295f754318336a07e85ec59bc",
                "width": 300,
            },
            {
                "height": 64,
                "url": "https://i.scdn.co/image/ab67616d0000485195f754318336a07e85ec59bc",
                "width": 64,
            },
        ],
        "name": "folklore",
        "release_date": "2020-07-24",
        "release_date_precision": "day",
        "total_tracks": 16,
        "type": "album",
        "uri": "spotify:album:2fenSS68JI1h4Fo296JfGr",
    },
    "artists": [
        {
            "external_urls": {
                "spotify": "https://open.spotify.com/artist/06HL4z0CvFAxyc27GXpf02"
            },
            "href": "https://api.spotify.com/v1/artists/06HL4z0CvFAxyc27GXpf02",
            "id": "06HL4z0CvFAxyc27GXpf02",
            "name": "Taylor Swift",
            "type": "artist",
            "uri": "spotify:artist:06HL4z0CvFAxyc27GXpf02",
        }
    ],
    "available_markets": [
        "AR",
        "AU",
        "AT",
        "BE",
        "BO",
        "BR",
        "BG",
        "CA",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DK",
        "DO",
        "DE",
        "EC",
        "EE",
        "SV",
        "FI",
        "FR",
        "GR",
        "GT",
        "HN",
        "HK",
        "HU",
        "IS",
        "IE",
        "IT",
        "LV",
        "LT",
        "LU",
        "MY",
        "MT",
        "MX",
        "NL",
        "NZ",
        "NI",
        "NO",
        "PA",
        "PY",
        "PE",
        "PH",
        "PL",
        "PT",
        "SG",
        "SK",
        "ES",
        "SE",
        "CH",
        "TW",
        "TR",
        "UY",
        "US",
        "GB",
        "AD",
        "LI",
        "MC",
        "ID",
        "JP",
        "TH",
        "VN",
        "RO",
        "IL",
        "ZA",
        "SA",
        "AE",
        "BH",
        "QA",
        "OM",
        "KW",
        "EG",
        "MA",
        "DZ",
        "TN",
        "LB",
        "JO",
        "PS",
        "IN",
        "BY",
        "KZ",
        "MD",
        "UA",
        "AL",
        "BA",
        "HR",
        "ME",
        "MK",
        "RS",
        "SI",
        "KR",
        "BD",
        "PK",
        "LK",
        "GH",
        "KE",
        "NG",
        "TZ",
        "UG",
        "AG",
        "AM",
        "BS",
        "BB",
        "BZ",
        "BT",
        "BW",
        "BF",
        "CV",
        "CW",
        "DM",
        "FJ",
        "GM",
        "GE",
        "GD",
        "GW",
        "GY",
        "HT",
        "JM",
        "KI",
        "LS",
        "LR",
        "MW",
        "MV",
        "ML",
        "MH",
        "FM",
        "NA",
        "NR",
        "NE",
        "PW",
        "PG",
        "WS",
        "SM",
        "ST",
        "SN",
        "SC",
        "SL",
        "SB",
        "KN",
        "LC",
        "VC",
        "SR",
        "TL",
        "TO",
        "TT",
        "TV",
        "VU",
        "AZ",
        "BN",
        "BI",
        "KH",
        "CM",
        "TD",
        "KM",
        "GQ",
        "SZ",
        "GA",
        "GN",
        "KG",
        "LA",
        "MO",
        "MR",
        "MN",
        "NP",
        "RW",
        "TG",
        "UZ",
        "ZW",
        "BJ",
        "MG",
        "MU",
        "MZ",
        "AO",
        "CI",
        "DJ",
        "ZM",
        "CD",
        "CG",
        "IQ",
        "LY",
        "TJ",
        "VE",
        "ET",
        "XK",
    ],
    "disc_number": 1,
    "duration_ms": 261922,
    "explicit": False,
    "external_ids": {"isrc": "USUG12002842"},
    "external_urls": {
        "spotify": "https://open.spotify.com/track/3hUxzQpSfdDqwM3ZTFQY0K"
    },
    "href": "https://api.spotify.com/v1/tracks/3hUxzQpSfdDqwM3ZTFQY0K",
    "id": "3hUxzQpSfdDqwM3ZTFQY0K",
    "is_local": False,
    "name": "august",
    "popularity": 85,
    "preview_url": "https://p.scdn.co/mp3-preview/8e82ad5f6e681af7f3b261417e4187d345a9530c?cid=ce931c51bc334b5288daa5e5ba897d5a",
    "track_number": 8,
    "type": "track",
    "uri": "spotify:track:3hUxzQpSfdDqwM3ZTFQY0K",
}


### other
{
    "added_at": "2023-05-01T23:34:36Z",
    "track": {
        "album": {
            "album_group": "single",
            "album_type": "single",
            "artists": [
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/5pDjmC5mRl7vDJhsjVwNfk"
                    },
                    "href": "https://api.spotify.com/v1/artists/5pDjmC5mRl7vDJhsjVwNfk",
                    "id": "5pDjmC5mRl7vDJhsjVwNfk",
                    "name": "Freya Ridings",
                    "type": "artist",
                    "uri": "spotify:artist:5pDjmC5mRl7vDJhsjVwNfk",
                }
            ],
            "available_markets": [
                "AE",
                "AG",
                "AO",
                "AR",
                "AU",
                "AZ",
                "BB",
                "BD",
                "BF",
                "BH",
                "BI",
                "BJ",
                "BN",
                "BO",
                "BR",
                "BS",
                "BT",
                "BW",
                "BZ",
                "CA",
                "CD",
                "CG",
                "CI",
                "CL",
                "CM",
                "CO",
                "CR",
                "CV",
                "CW",
                "DJ",
                "DM",
                "DO",
                "DZ",
                "EC",
                "EG",
                "ET",
                "FJ",
                "FM",
                "GA",
                "GB",
                "GD",
                "GH",
                "GM",
                "GN",
                "GQ",
                "GT",
                "GW",
                "GY",
                "HK",
                "HN",
                "HT",
                "ID",
                "IE",
                "IN",
                "IQ",
                "JM",
                "JO",
                "JP",
                "KE",
                "KH",
                "KI",
                "KM",
                "KN",
                "KR",
                "KW",
                "LA",
                "LB",
                "LC",
                "LK",
                "LR",
                "LS",
                "LY",
                "MA",
                "MG",
                "MH",
                "ML",
                "MN",
                "MO",
                "MR",
                "MU",
                "MV",
                "MW",
                "MX",
                "MY",
                "MZ",
                "NA",
                "NE",
                "NG",
                "NI",
                "NP",
                "NR",
                "NZ",
                "OM",
                "PA",
                "PE",
                "PG",
                "PH",
                "PK",
                "PS",
                "PW",
                "PY",
                "QA",
                "RW",
                "SA",
                "SB",
                "SC",
                "SG",
                "SL",
                "SN",
                "SR",
                "ST",
                "SV",
                "SZ",
                "TD",
                "TG",
                "TH",
                "TL",
                "TN",
                "TO",
                "TT",
                "TV",
                "TW",
                "TZ",
                "UG",
                "US",
                "UY",
                "VC",
                "VE",
                "VN",
                "VU",
                "WS",
                "ZA",
                "ZM",
                "ZW",
            ],
            "external_urls": {
                "spotify": "https://open.spotify.com/album/5e811Cmtlnt225AQO1tIiu"
            },
            "href": "https://api.spotify.com/v1/albums/5e811Cmtlnt225AQO1tIiu",
            "id": "5e811Cmtlnt225AQO1tIiu",
            "images": [
                {
                    "height": 640,
                    "url": "https://i.scdn.co/image/ab67616d0000b273e568d8f337e495d1bd9e83d1",
                    "width": 640,
                },
                {
                    "height": 300,
                    "url": "https://i.scdn.co/image/ab67616d00001e02e568d8f337e495d1bd9e83d1",
                    "width": 300,
                },
                {
                    "height": 64,
                    "url": "https://i.scdn.co/image/ab67616d00004851e568d8f337e495d1bd9e83d1",
                    "width": 64,
                },
            ],
            "name": "Face in the Crowd",
            "release_date": "2023-02-17",
            "release_date_precision": "day",
            "total_tracks": 2,
            "type": "album",
            "uri": "spotify:album:5e811Cmtlnt225AQO1tIiu",
        },
        "artists": [
            {
                "external_urls": {
                    "spotify": "https://open.spotify.com/artist/5pDjmC5mRl7vDJhsjVwNfk"
                },
                "href": "https://api.spotify.com/v1/artists/5pDjmC5mRl7vDJhsjVwNfk",
                "id": "5pDjmC5mRl7vDJhsjVwNfk",
                "name": "Freya Ridings",
                "type": "artist",
                "uri": "spotify:artist:5pDjmC5mRl7vDJhsjVwNfk",
            }
        ],
        "available_markets": [
            "AR",
            "AU",
            "BO",
            "BR",
            "CA",
            "CL",
            "CO",
            "CR",
            "DO",
            "EC",
            "SV",
            "GT",
            "HN",
            "HK",
            "IE",
            "MY",
            "MX",
            "NZ",
            "NI",
            "PA",
            "PY",
            "PE",
            "PH",
            "SG",
            "TW",
            "UY",
            "US",
            "GB",
            "ID",
            "JP",
            "TH",
            "VN",
            "ZA",
            "SA",
            "AE",
            "BH",
            "QA",
            "OM",
            "KW",
            "EG",
            "MA",
            "DZ",
            "TN",
            "LB",
            "JO",
            "PS",
            "IN",
            "KR",
            "BD",
            "PK",
            "LK",
            "GH",
            "KE",
            "NG",
            "TZ",
            "UG",
            "AG",
            "BS",
            "BB",
            "BZ",
            "BT",
            "BW",
            "BF",
            "CV",
            "CW",
            "DM",
            "FJ",
            "GM",
            "GD",
            "GW",
            "GY",
            "HT",
            "JM",
            "KI",
            "LS",
            "LR",
            "MW",
            "MV",
            "ML",
            "MH",
            "FM",
            "NA",
            "NR",
            "NE",
            "PW",
            "PG",
            "WS",
            "ST",
            "SN",
            "SC",
            "SL",
            "SB",
            "KN",
            "LC",
            "VC",
            "SR",
            "TL",
            "TO",
            "TT",
            "TV",
            "VU",
            "AZ",
            "BN",
            "BI",
            "KH",
            "CM",
            "TD",
            "KM",
            "GQ",
            "SZ",
            "GA",
            "GN",
            "LA",
            "MO",
            "MR",
            "MN",
            "NP",
            "RW",
            "TG",
            "ZW",
            "BJ",
            "MG",
            "MU",
            "MZ",
            "AO",
            "CI",
            "DJ",
            "ZM",
            "CD",
            "CG",
            "IQ",
            "LY",
            "VE",
            "ET",
        ],
        "disc_number": 1,
        "duration_ms": 204503,
        "explicit": False,
        "external_ids": {"isrc": "UK8E21907404"},
        "external_urls": {
            "spotify": "https://open.spotify.com/track/0V9QY6NnXtAMwjltgMP0pl"
        },
        "href": "https://api.spotify.com/v1/tracks/0V9QY6NnXtAMwjltgMP0pl",
        "id": "0V9QY6NnXtAMwjltgMP0pl",
        "is_local": False,
        "name": "Face in the Crowd",
        "popularity": 57,
        "preview_url": "https://p.scdn.co/mp3-preview/d0adb4905179bed65c120367e859047f73a5ce55?cid=ce931c51bc334b5288daa5e5ba897d5a",
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:0V9QY6NnXtAMwjltgMP0pl",
    },
}
